# Generated by Django 2.1.1 on 2018-09-30 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=20)),
                ('introduction', models.TextField()),
                ('credit', models.IntegerField()),
                ('photo', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=20)),
                ('courseTimes', models.IntegerField()),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('classTime', models.DateTimeField()),
                ('semester', models.CharField(max_length=20)),
                ('isDelets', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
                'ordering': ['credit'],
            },
        ),
        migrations.CreateModel(
            name='studentLinkCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.IntegerField()),
                ('courseId', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'studentLinkCourse',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='teacherLinkCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherId', models.IntegerField()),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teachersLinkCourse',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.BooleanField()),
                ('photo', models.CharField(max_length=128)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'teachers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.BooleanField()),
                ('credit', models.IntegerField()),
                ('photo', models.CharField(max_length=128)),
                ('major', models.CharField(max_length=20)),
                ('isDelete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
    ]
